params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: path

  network:
    name: actor_critic
    separate: False
    normalization: 'layer_norm'
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 
      regularizer:
        name: 'None'
      convs:    
        - filters: 16
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 32
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 32
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [128]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: glorot_normal_initializer
        gain: 1.4142 
    rnn:
      name: 'lstm'
      units: 128
      layers: 1
      before_mlp: False
  config:
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.9
    learning_rate: 5e-4
    name: minigrid_env_rnn
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True
    env_name:  minigrid_env
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 512
    mini_epochs: 8
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.008
    normalize_input: True
    seq_len: 16
    weight_decay: 0.0001

    env_config:
      #action_bonus: True
      name: MiniGrid-MemoryS7-v0
