params:  
  seed: 8
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128,64]
      d2rl: False
      activation: relu
      initializer:
        name: default
        scale: 2         
      
  config:
      reward_shaper:
        min_val: -1
        scale_value: 0.1

      normalize_advantage: True
      gamma: 0.995
      tau: 0.95
      learning_rate: 5e-4
      name: walker_ppg
      score_to_win: 290
      grad_norm: 0.5
      entropy_coef: 0 #-0.005
      truncate_grads: False
      env_name:  BipedalWalker-v3
      ppo: True
      e_clip: 0.2
      clip_value: False
      num_actors: 16
      horizon_length: 256
      minibatch_size: 1024
      mini_epochs: 1
      critic_coef: 2
      schedule_type: 'standard'
      lr_schedule: adaptive
      kl_threshold: 0.004
      normalize_input: False
      bounds_loss_coef: 0.0005
      max_epochs: 10000
      normalize_value: True
      #weight_decay: 0.0001
      phasic_policy_gradients:
        learning_rate: 5e-4
        minibatch_size: 1024
        mini_epochs: 6
      player:
        render: True
        determenistic: True
        games_num: 200
