params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          # pytorch
          name: variance_scaling_initializer
          scale: 0.02

          # tf
        #  name: normc_initializer
        #  std: 0.01
        sigma_init:
          name: const_initializer
          # value: 0 # tf 
          val: 0 # pytorch

        fixed_sigma: True
    mlp:
      units: [256,128,64]
      activation: elu

      initializer:
        # pytorch
        name: variance_scaling_initializer
        scale: 2

      # tf
      #  name: normc_initializer
      #  std: 1
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False
  load_path: 'nn/humanoid_torch.pth'

  config:
    reward_shaper:
      scale_value: 0.1
    normalize_advantage : True
    gamma : 0.99
    tau : 0.95
    learning_rate : 3e-4
    name : 'humanoid_torch'
    score_to_win : 20000
    grad_norm : 0.5
    entropy_coef : 0.0
    truncate_grads : True
    env_name : FlexHumanoid
    ppo : True
    e_clip : 0.2
    num_actors : 256
    steps_num : 32
    minibatch_size : 4096
    mini_epochs : 4
    critic_coef : 1
    clip_value : False
    lr_schedule : adaptive
    lr_threshold : 0.01
    normalize_input : False
    normalize_reward : True
    bounds_loss_coef: 0.000
    max_epochs: 12000