params:  
  seed: 8
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128,64]
      d2rl: False
      activation: elu
      initializer:
        name: default
        scale: 2

  load_checkpoint: False
  load_path: './nn/last_walkerep=10001rew=108.35405.pth'

  config:
      reward_shaper:
        min_val: -1
        scale_value: 0.1

      normalize_advantage: True
      gamma: 0.995
      tau: 0.95
      learning_rate: 3e-4
      name: walker
      score_to_win: 300
      grad_norm: 1.0
      entropy_coef: 0
      truncate_grads: True
      env_name:  BipedalWalker-v3
      ppo: True
      e_clip: 0.2
      clip_value: False
      num_actors: 16
      horizon_length: 512
      minibatch_size: 1024
      mini_epochs: 4
      critic_coef: 4
      schedule_type: 'standard'
      lr_schedule: adaptive
      kl_threshold: 0.008
      normalize_input: True
      bounds_loss_coef: 0.00
      max_epochs: 10000
      normalize_value: True
      use_diagnostics: True
      ewma_ppo: False
      #weight_decay: 0.0001
      player:
        render: True
        determenistic: True
        games_num: 200
