params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02 
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128, 64]
      d2rl: False
      activation: relu
      initializer:
        name: default         
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001
  load_checkpoint: False
  load_path: './nn/multiwalker.pth'

  config:
      reward_shaper:
        min_val: -1
        scale_value: 0.1

      normalize_advantage: True
      gamma: 0.995
      tau: 0.95
      learning_rate: 3e-4
      name: multiwalker
      score_to_win: 300
      grad_norm: 0.5
      entropy_coef: 0
      truncate_grads: True
      env_name:  multiwalker_env
      ppo: True
      e_clip: 0.2
      use_experimental_cv: False
      clip_value: False
      num_actors: 16
      steps_num: 256
      minibatch_size: 1536
      mini_epochs: 4
      critic_coef: 1
      schedule_type: 'standard'
      lr_schedule: None
      lr_threshold: 0.008
      normalize_input: True
      bounds_loss_coef: 0.0001
      max_epochs: 3000
      weight_decay: 0.0000

      player:
        render: True
        games_num: 200

      env_config:
        central_value: True
        use_prev_actions: True
      central_value_config:
        minibatch_size: 512
        mini_epochs: 4
        lr: 3e-4
        clip_value: False
        normalize_input: True
        truncate_grads: False
        network:
          name: actor_critic
          central_value: True
          mlp:
            units: [512, 256, 128]
            activation: elu
            initializer:
              name: default