params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 

  network:
    name: actor_critic
    separate: False
    value_shape: 2
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [256, 512]
      activation: elu
      regularizer:
        name: 'None'
      initializer:
        name: variance_scaling_initializer
        scale: 2 
  config:
    reward_shaper:
        scale_value: 1.0
        
    normalize_advantage: True
    gamma: 0.999
    tau: 0.9
    learning_rate: 1e-4
    name: atari
    score_to_win: 900
    grad_norm: 0.5
    entropy_coef: 0.002
    truncate_grads: True
    env_name: atari_gym
    ppo: true
    e_clip: 0.1
    clip_value: True
    num_actors: 32
    steps_num: 512
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.008
    normalize_input: True
    seq_len: 8
    #lr_schedule:  adaptive
    # lr_threshold: 0.008
    # bounds_loss_coef: 0.5
    # max_epochs: 5000
    env_config:
      name: MontezumaRevengeNoFrameskip-v4
    
    rnd_config:
        scale_value: 1.0
        episodic: True
        episode_length: 256
        gamma: 0.99
        mini_epochs: 2
        minibatch_size: 1024
        lr: 1e-4
        network:
          name: rnd_curiosity
          cnn:
              type: conv2d
              activation: elu
              initializer:
                name: variance_scaling_initializer
                scale: 2
              regularizer:
                name: 'None'
              rnd:
                convs:    
                  - filters: 32
                    kernel_size: 8
                    strides: 4
                    padding: 0
                  - filters: 64
                    kernel_size: 4
                    strides: 2
                    padding: 0
                  - filters: 64
                    kernel_size: 3
                    strides: 1
                    padding: 0
              net:
                convs:    
                  - filters: 32
                    kernel_size: 8
                    strides: 4
                    padding: 0
                  - filters: 64
                    kernel_size: 4
                    strides: 2
                    padding: 0
                  - filters: 64
                    kernel_size: 3
                    strides: 1
                    padding: 0
          mlp:
              rnd:
                units: [512,512, 512]
              net:
                units: [512]
              activation: elu
              regularizer:
                name: 'None'
              initializer:
                name: variance_scaling_initializer
                scale: 2