params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: variance_scaling_initializer
          scale: 0.02 
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2         
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001
    lstm:
      units: 128
      concated: False    
  load_checkpoint: False
  load_path: './nn/last_walkerep=10001rew=108.35405.pth'

  config:
      reward_shaper:
        scale_value: 0.1

      normalize_advantage: True
      gamma: 0.99
      tau: 0.9
      learning_rate: 1e-4
      name: walker
      score_to_win: 280
      grad_norm: 0.5
      entropy_coef: 0.000
      truncate_grads: True
      env_name:  BipedalWalkerHardcore-v3
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      steps_num: 256
      minibatch_size: 2048
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  None
      lr_threshold: 0.008
      normalize_input: True
      seq_len: 16
      bounds_loss_coef: 0.0
      max_epochs: 100000


experiment_config1:
  start_exp: 0
  start_sub_exp: 0
  experiments:
    - exp:
      - path: config.bounds_loss_coef
        value: [0.5]
