params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: variance_scaling_initializer
          scale: 0.02 
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128, 64]
      d2rl: True
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2         
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001
  load_checkpoint: False
  load_path: './nn/last_walkerep=10001rew=108.35405.pth'

  config:
      reward_shaper:
        min_val: -1
        scale_value: 0.1

      normalize_advantage: True
      gamma: 0.995
      tau: 0.95
      learning_rate: 3e-4
      name: walker
      score_to_win: 300
      grad_norm: 0.5
      entropy_coef: 0
      truncate_grads: True
      env_name:  BipedalWalker-v3
      ppo: True
      e_clip: 0.2
      clip_value: False
      num_actors: 16
      steps_num: 256
      minibatch_size: 1024
      mini_epochs: 4
      critic_coef: 4
      schedule_type: 'standard'
      lr_schedule: adaptive
      lr_threshold: 0.008
      normalize_input: False
      seq_length: 16
      bounds_loss_coef: 0.00
      max_epochs: 10000
      normalize_value: True
      #weight_decay: 0.0001

      player:
        render: False
        determenistic: True
        games_num: 200
