params:
  algo:
    name: dqn

  model:
    name: dqn

  load_checkpoint: False
  load_path: 'nn/breakoutep=3638750.0rew=201.75'

  network:
    name: dqn
    dueling: True
    atoms: 51
    noisy: True
    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 'valid'
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 'valid'
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'valid'
      
    mlp:
      units: [256]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
  config:
    reward_shaper:
        scale_value: 1
    gamma : 0.99
    learning_rate : 0.0001
    steps_per_epoch : 4
    batch_size : 32
    epsilon : 0.00
    min_epsilon : 0.00
    epsilon_decay_frames : 1000000
    num_epochs_to_copy : 10000
    name : 'breakout'
    env_name: BreakoutNoFrameskip-v4
    is_double : True
    score_to_win : 600
    num_steps_fill_buffer : 100000
    replay_buffer_type : 'prioritized'
    replay_buffer_size : 1000000
    priority_beta : 0.4
    priority_alpha : 0.6
    beta_decay_frames : 1000000
    max_beta : 1
    steps_num : 3
    episodes_to_log : 100
    lives_reward : 5
    atoms_num : 51
    v_min : -10
    v_max : 10
    games_to_track : 100
    lr_schedule : None
    max_epochs: 10000000
