params:  
  algo:
    name: vmpo_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    space:
      discrete:
    mlp:
      units: [64,64]
      activation: relu
      initializer:
          name: default
          scale: 2

  load_checkpoint: False
  load_path: path

  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.95

      learning_rate: 8e-4
      name: vmpo_cartpole
      score_to_win: 500

      grad_norm: 10
      entropy_coef: 0.00
      truncate_grads: True
      env_name:  CartPole-v1 #LunarLander-v2
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      horizon_length: 128
      minibatch_size: 2048
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  None
      kl_threshold: 0.008
      schedule_type: standard
      normalize_input: False
      seq_length: 4
      bounds_loss_coef: 0

      player:
        render: True
