params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default
  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.995
      tau: 0.95

      learning_rate: 3e-4
      name: mujoco_gym
      score_to_win: 2000

      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: True
      env_name:  openai_gym
      ppo: true
      e_clip: 0.2
      clip_value: False
      num_actors: 16
      horizon_length: 256
      minibatch_size: 512
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  adaptive
      kl_threshold: 0.008
      schedule_type: 'standard'
      normalize_input: True
      normalize_value: True
      value_bootstrap: True
      bounds_loss_coef: 0.000

      env_config:
        name: HalfCheetah-v2
        #flat_observation: True

      player:
        render: True