params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: variance_scaling_initializer
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: False

    cnn:
      type: conv1d
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 1
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 1
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 1
        - filters: 128
          kernel_size: 2
          strides: 1
          padding: 0
    mlp:
      units: [128, 64]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False
  load_path: path

  config:
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9

      learning_rate: 1e-4
      name: humanoid_conv
      score_to_win: 15000

      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: True
      env_name:  dm_control
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      steps_num: 1024
      minibatch_size: 8192
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  adaptive
      lr_threshold: 0.008

      normalize_input: False
      seq_len: 8
      bounds_loss_coef: 0.001

      env_config:
        frames: 4
        name: Humanoid2Run-v0
        flat_observation: True
      