params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c_lstm

  load_checkpoint: False
  load_path: 'nn/2s_vs_1c_lstm'

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:
      
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name: 'None'
    lstm:
      units: 128
      concated: False
  config:
    name: 2m_vs_1z
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  smac
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: True

    env_config:
      name: 2m_vs_1z
      frames: 1
      random_invalid_step: False