params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/sc2smac_cnn'

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:
      
    cnn:
      type: conv1d
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 256
          kernel_size: 3
          strides: 1
          padding: 1
        - filters: 512
          kernel_size: 3
          strides: 1
          padding: 1
        - filters: 1024
          kernel_size: 3
          strides: 1
          padding: 1
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: glorot_normal_initializer
        gain: 1.4241 
      regularizer:
        name:  'None'
  config:
    name: MMM2_cnn
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  smac_cnn
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 64
    minibatch_size: 2560
    mini_epochs: 1
    critic_coef: 2
    lr_schedule:  adaptive
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: True
    ignore_dead_batches : False

    env_config:
      name: MMM2
      frames: 4
      transpose: False
      random_invalid_step: False