params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/last_3s_vs_5z_cvep=10001rew=9.585825.pth'

  network:
    name: actor_critic
    separate: False
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'

  config:
    name: 3s_vs_5z_cv
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True
    env_name:  smac
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 1536 # 3 * 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: True
    use_action_masks: True
    max_epochs: 50000


    central_value_config:
      minibatch_size: 512
      mini_epochs: 4
      lr: 5e-4
      clip_value: False
      normalize_input: True
      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 256,128]
          activation: relu
          initializer:
            name: variance_scaling_initializer
            scale: 2 
          regularizer:
            name:  'None'

    env_config:
      name: 3s_vs_5z
      frames: 1
      transpose: False
      random_invalid_step: False
      central_value: True
      reward_only_positive: False
      obs_last_action: True
