params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/5m_vs_6m_cv.pth'

  network:
    name: actor_critic
    separate: False
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [512, 256, 128]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'

  config:
    name: 5m_vs_6m_cv
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.001
    truncate_grads: True
    env_name:  smac
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 2560 # 5 * 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: True
    normalize_reward: False
    use_action_masks: True
    ignore_dead_batches : False
    #max_epochs: 10000

    central_value_config:
      use_joint_obs_actions: True
      minibatch_size: 512
      mini_epochs: 4
      lr: 5e-4
      clip_value: False
      normalize_input: True
      network:
        normalization: batch_norm
        joint_obs_actions:
            embedding: False
            embedding_scale: 1 #(actions // embedding_scale)
            mlp_scale: 4 # (mlp from obs size) // mlp_out_scale
        name: actor_critic
        central_value: True
        mlp:
          units: [256, 128,64]
          activation: relu
          initializer:
            name: variance_scaling_initializer
            scale: 2 
          regularizer:
            name:  'None'

    env_config:
      name: 5m_vs_6m
      central_value: True
      reward_only_positive: True
      obs_last_action: True
      apply_agent_ids: True
      
      #reward_negative_scale: 0.1