params:  
  seed: 322
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c


  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: elu
      initializer:
        name: glorot_normal_initializer
        gain: 1
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: elu
      initializer:
        name: glorot_normal_initializer
        gain: 1
  config:
    reward_shaper:
      min_val: -1
      max_val: 1
    normalize_advantage: True
    gamma: 0.995
    tau: 0.9
    learning_rate: 5e-4
    name: pong_ppg
    score_to_win: 20.5
    grad_norm: 10
    entropy_coef: 0.01
    truncate_grads: True
    env_name:  PongNoFrameskip-v4
    ppo: true
    e_clip: 0.2
    clip_value: False
    num_actors: 24
    horizon_length: 128
    minibatch_size: 256
    mini_epochs: 1
    critic_coef: 1
    lr_schedule:  none
    #kl_threshold: 0.008
    #schedule_entropy : True
    normalize_value: False 
    normalize_input: False
    max_epochs: 1500
    phasic_policy_gradients:
        learning_rate: 5e-4
        minibatch_size: 256
        mini_epochs: 6
        n_aux: 16
        kl_coef: 1.0
    player:
      render: True
      games_num: 100
      n_game_life: 1
      determenistic: True