params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c



  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237 
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
  config:
    reward_shaper:
      min_val: -1
      max_val: 1
      scale_value: 1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.9
    learning_rate: 3e-4
    name: breakout_ppg
    score_to_win: 900
    grad_norm: 10
    entropy_coef: 0.01
    truncate_grads: True
    env_name: atari_gym
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 24
    horizon_length: 128
    minibatch_size: 512
    mini_epochs: 1
    critic_coef: 1
    lr_schedule:  adaptive
    kl_threshold: 0.008
    #lr_schedule:  linear
    #schedule_entropy: True
    normalize_value: True
    normalize_input: False
    max_epochs: 20000
    phasic_policy_gradients:
        learning_rate: 5e-4
        minibatch_size: 512
        mini_epochs: 6
        n_aux: 16
        kl_coef: 1.0
    env_config:
      skip: 4
      name: 'BreakoutNoFrameskip-v4'
      episode_life: True

    player:
      render: True
      games_num: 200
      n_game_life: 5
      determenistic: False