params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c



  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      permute_input: False
      type: conv2d
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
      convs:
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0

    mlp:
      units: [512]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
  config:
    reward_shaper:
      min_val: -1
      max_val: 1
      scale_value: 1

    normalize_advantage: True
    gamma: 0.999
    tau: 0.95
    learning_rate: 8e-4
    name: breakout_ppo
    score_to_win: 900
    grad_norm: 10
    entropy_coef: 0.01
    truncate_grads: True
    env_name:  envpool
    ppo: true
    e_clip: 0.2
    clip_value: False
    num_actors: 16
    horizon_length: 256
    minibatch_size: 512
    mini_epochs: 2
    critic_coef: 1
    lr_schedule:  None
    kl_threshold: 0.01
    #lr_schedule:  linear
    #schedule_entropy: True
    normalize_value: True
    normalize_input: False
    max_epochs: 3000
    use_diagnostics: True
    env_config:
      env_name: 'Breakout-v5'
      episodic_life: True

    player:
      render: False
      games_num: 200
      n_game_life: 5
      determenistic: False