params:
  seed: 42
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: resnet_actor_critic
    require_rewards: True
    require_last_actions: True
    separate: False
    value_shape: 1
    space: 
      discrete:
    
    cnn:
      permute_input: False
      conv_depths: [16, 32, 32]
      activation: relu
      initializer:
        name: default
      regularizer:
        name: 'None'
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: default 
    rnn:
      name: lstm
      units: 256
      layers: 1

  config:
    name: Pong-v5_envpool_resnet_16_seq_length
    env_name: envpool
    reward_shaper:
      min_val: -1
      max_val: 1
    normalize_input: False
    mixed_precision: False
    normalize_value: True
    normalize_advantage: True
    value_bootstrap: False
    gamma: 0.995
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: None
    kl_threshold: 0.01
    score_to_win: 20
    truncate_grads: True
    grad_norm: 1.5
    entropy_coef: 0.01
    e_clip: 0.2
    clip_value: True
    num_actors: 64
    horizon_length: 128
    minibatch_size: 2048
    mini_epochs: 2
    critic_coef: 1
    seq_length: 16
    max_epochs: 1000
    use_diagnostics: True

    env_config:
      env_name: Pong-v5
      has_lives: False
      use_dict_obs_space: True

    player:
        render: True
        games_num: 100
        n_game_life: 1
        deterministic: True

