params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn'

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [64,64]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'
  config:
    name: slime
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  slime_gym
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: False
    ignore_dead_batches : False


    env_config:
      name: SlimeVolleyDiscrete-v0