params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/slime_pvp.pth'

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [128,64]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'
  config:
    name: slime_pvp2
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.995
    tau: 0.95
    learning_rate: 2e-4
    score_to_win: 100
    grad_norm: 0.5
    entropy_coef: 0.01
    truncate_grads: True
    env_name:  slime_gym
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 512
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    games_to_track: 1000

    self_play_config:
      update_score: 1.3
      games_to_check: 100

    env_config:
      name: SlimeVolleyDiscrete-v0
      #neg_scale: 1 #0.5
      self_play: False