params:
  algo:
    name: dqn

  model:
    name: dqn

  load_checkpoint: False
  load_path: path

  network:
    name: dqn
    dueling: True
    atoms: 1
    noisy: False
    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 'valid'
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 'valid'
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'valid'
      
    mlp:
      units: [256]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
  config:
    reward_shaper:
        scale_value: 0.1

    gamma : 0.99
    learning_rate : 0.0005
    steps_per_epoch : 4
    batch_size : 128
    epsilon : 0.90
    min_epsilon : 0.02
    epsilon_decay_frames : 100000
    num_epochs_to_copy : 10000
    name : 'pong_dddqn_config1'
    env_name:  PongNoFrameskip-v4
    is_double : True
    score_to_win : 20.9
    num_steps_fill_buffer : 10000
    replay_buffer_type : 'normal'
    replay_buffer_size : 100000
    priority_beta : 0.4
    priority_alpha : 0.6
    beta_decay_frames : 100000
    max_beta : 1
    steps_num : 3
    episodes_to_log : 10
    lives_reward : 1
    atoms_num : 1
    games_to_track : 20
    lr_schedule : polynom_decay
    max_epochs: 100000

experiment_config:
  start_exp: 0
  start_sub_exp: 3
  experiments:
#    - exp:
#      - path: config.learning_rate
#        value: [0.0005, 0.0002]
    - exp:
      - path: network.initializer
        value:
          - name: variance_scaling_initializer
            scale: 2
          - name: glorot_normal_initializer
          - name: glorot_uniform_initializer
          - name: orthogonal_initializer
            gain: 1.41421356237
      - path: network.cnn.initializer
        value:
          - name: variance_scaling_initializer
            scale: 2
          - name: glorot_normal_initializer
          - name: glorot_uniform_initializer
          - name: orthogonal_initializer
            gain: 1.41421356237


