params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/sc2smac_cnn'

  network:
    name: actor_critic
    separate: True
    normalization: layer_norm
    space: 
      discrete:
      
    cnn:
      type: conv1d
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 128
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 128
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 256
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 512
          kernel_size: 3
          strides: 1
          padding: 'valid'
    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'
  config:
    name: sc2
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  smac_cnn
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 256
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: True
    ignore_dead_batches : True

    env_config:
      name: 3m
      frames: 4
      transpose: False