params:
  seed: 7

  #devices: [0, 0]

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: PickCube_State_Maniskill
    full_experiment_name: PickCube_State_Maniskill
    env_name: maniskill
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    use_smooth_clamp: False
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 1000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    num_actors: 1024
    minibatch_size: 4096
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    bounds_loss_coef: 0.0001

    env_config:
      env_name: PickCube-v1
      obs_mode: "state" # there is also "state_dict", "rgbd", ...
      control_mode: "pd_ee_delta_pose" # there is also "pd_joint_delta_pos", ..
